### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [nhantran3395/scrapper#43]
Hello Nhan 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I will be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

**Comment by olivierobert** [comment]
I have completed the first round of review. I focused on the core issue that can be tackled in the short time we have :-) There are other areas of improvement, such as code style and frontend issues, but let's focus on the six issues for now.

Looking forward to your feedback on the opened issues.

**Comment by nhantran3395** [comment]
Hi @olivierobert : Thank you for the code review

I will address the issues that were opened one by one. Right now, I have put a few comments on all of them.

This week, because the clients in my current project are coming to visit and have more discussions and plans for next year, I will come to the office the whole week and have less time to work on the feedback than usual.

I need an extra 2-3 more days to address all the issues and feedback that are open.
Below is my plan to work on them:

```
Mon (9th Oct):
- Address #45, #48 Progress: Raised PR #49 #50  

Tue and Wed 
- Address #46

Thu to Next Mon (16th Oct)
- Address #44 and #47 
```

Is it okay if we work on this review process until next Monday (16th)?

**Comment by olivierobert** [comment]
HI @nhantran3395, I have reviewed your feedback on the issues. As for the next step, it is great you provided such a detailed plan but I am wary of using so much of your time. The goal is not necessarily to have fixes for all raised concerns but to have your feedback and ideas on how to solve them. 

So, let's discard #47 as this would require much effort. Adding tests might entail architectural changes. For #44, I am primarily interested in how you would set it up. You can limit yourself to describing the architecture of the implementation. As for #46, since you already started, you could try to finish it. 

Let's aim to close the code review by tomorrow. Let me know if that is possible.

**Comment by nhantran3395** [comment]
> HI @nhantran3395, I have reviewed your feedback on the issues. As for the next step, it is great you provided such a detailed plan but I am wary of using so much of your time. The goal is not necessarily to have fixes for all raised concerns but to have your feedback and ideas on how to solve them.
> 
> So, let's discard #47 as this would require much effort. Adding tests might entail architectural changes. For #44, I am primarily interested in how you would set it up. You can limit yourself to describing the architecture of the implementation. As for #46, since you already started, you could try to finish it.
> 
> Let's aim to close the code review by tomorrow. Let me know if that is possible.

Hi @olivierobert : Noted on this. I will complete #46 and describe the architecture of the implementation in #44 today. Yesterday was full, I could not work on the feedback.

I will finish the remains today and we can wrap up the review process tomorrow (Thu).

**Comment by nhantran3395** [comment]
Hi @olivierobert : I have submitted the PR for #46 and added comments about the implementation plan in #44. Please let me know if you have any comments or feedback.

**Comment by olivierobert** [comment]
Thanks for the updates @nhantran3395. It would be great to have your final feedback on #44 and in the mean time I will wrap up the assessment to proceed with the next stage.

**Comment by nhantran3395** [comment]
Hi @olivierobert : I added a comment to explain more details in #44 and updated the PR in #51 to fix the typo. Please have a look
