### ISSUE TITLE
[Bug] Empty keywords can be added to the database

### ISSUE THREAD

**Issue by olivierobert** [nhantran3395/scrapper#45]
## Issue

When uploading a file with an empty line break

```csv
ruby on rails
elixir phoenix

```

The empty line is treated as a valid keyword:

<img width="1457" alt="image" src="https://github.com/nhantran3395/scrapper/assets/696529/c774028e-11f8-42f4-a599-a204295fe030">

## Expected

- The CSV file is adequately validated
- An empty string must not be a valid keyword

**Comment by nhantran3395** [comment]
Good catch! Let me fix it

**Comment by nhantran3395** [comment]
Hi Olivier @olivierobert: I raised a PR https://github.com/nhantran3395/scrapper/pull/50 to fix this issue. Please take a look.
