### ISSUE TITLE
[Chore] DRY UI layouts 

### ISSUE THREAD

**Issue by olivierobert** [nhantran3395/scrapper#46]
## Issue

The layout component is very minimal:

https://github.com/nhantran3395/scrapper/blob/448ebb7f173de08329614fbc14c41673c7099651/apps/web/src/components/common/layout/layout.tsx#L7

As a result, all pages now repeat the code for the layout that includes the navigation bar, the loading notifications, etc.

https://github.com/nhantran3395/scrapper/blob/448ebb7f173de08329614fbc14c41673c7099651/apps/web/src/components/details/details.tsx#L39-L41

https://github.com/nhantran3395/scrapper/blob/448ebb7f173de08329614fbc14c41673c7099651/apps/web/src/components/keywords/keywords.tsx#L49-L51

## Expected

Ensure there is a layout to with all shared components

> [!Note]
> There can be two layout file: one for auth pages and another one for the other pages.

**Comment by nhantran3395** [comment]
Good point. I will do the cleanup and open a PR.

**Comment by nhantran3395** [comment]
Hi Olivier, I opened #51 to work on this issue. I will be adding the tests and completing this PR tomorrow.
