### ISSUE TITLE
[Chore] Increase test coverage

### ISSUE THREAD

**Issue by olivierobert** [nhantran3395/scrapper#47]
## Issue

Automated tests do not cover the core business logic (CSV upload, scraping).

## Expected

While 100% test coverage is not required for this code challenge, all critical paths of the application should be unit-tested (and, ideally, UI-tested). So the following should be covered:

- CSV parsing
- Keyword creation
- Keyword scraping
- Keyword listing

**Comment by nhantran3395** [comment]
Sure! Testing was overlooked during the development of the challenge.
Let me add the tests, I will work on this in a PR.
